# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YB-4-IeJnrHh7IuSW27m3HnxgRrkjgvI

# Day 1
I learned about printing, commenting, input, variables and string manipulation.
"""

print("Hello World!")      #function to print on the console

print("Day 1 - Python Print Functoin")
print("The function is declared like this:")   #syntax
print("print('what to print')")

print("Hello world!\nHello world!")  #add \n to go to next line

print("Hello" + " LucK")   #String concatenation

print("Hello " + input("What is your name?\n"))  #here the input function runs first

str1 = input("What is your name?\n")
count = 0
for i in str1:                               #my answer for length of string
  count+=1
print(count)

str1 = input("What is your name?\n")
len(str1)                                    #len function returns the length of the object

a = 1
b = 2

print("a: " , a)
print("b: " , b)

temp = a
a = b                                           #swapping the values
b = temp

print("After swapping")
print("a: " , a)
print("b: " , b)

#Band name generator

n1 = input("What's name of your city?\n")
n2 = input("What's name of your pet?\n")
print("Your band name is : " , n1 + " " + n2)